export const REQUEST_POSTS_LOADING = 'REQUEST_POSTS_LOADING';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAIL = 'REQUEST_POSTS_FAIL';

export const TOGGLE_SELECT_POST = 'TOGGLE_SELECT_POST';
